import type { StrictLintConfig } from "./schema.js";

/** Layout primitives with no design-system equivalent. Always renderable. */
export const LAYOUT_ELEMENTS = [
  "div", "span", "section", "article", "header", "footer", "main", "nav", "aside", "hgroup",
  "ul", "ol", "li", "dl", "dt", "dd", "p", "br", "hr", "pre", "blockquote", "figure", "figcaption",
  "h1", "h2", "h3", "h4", "h5", "h6",
  "strong", "em", "b", "i", "u", "s", "small", "mark", "sub", "sup", "code", "kbd", "samp", "var",
  "abbr", "cite", "dfn", "q", "time", "data", "address", "ins", "del", "wbr", "bdi", "bdo",
  "img", "picture", "source", "video", "audio", "track", "canvas", "iframe", "embed", "object",
  "svg", "path", "circle", "ellipse", "rect", "line", "polyline", "polygon", "g", "defs", "use",
  "mask", "clipPath", "linearGradient", "radialGradient", "stop", "text", "tspan", "symbol",
  "form", "fieldset", "legend", "output",
  "html", "head", "body", "title", "meta", "link", "style", "script", "noscript", "base",
  "template", "slot", "portal",
];

/** Native tags that a design system is expected to own, mapped to their replacement. */
export const DEFAULT_DENIED_ELEMENTS: Record<string, string> = {
  button: "`Button` from `@/components/ui/button`",
  input: "`Input` from `@/components/ui/input` (or `Checkbox`, `Switch`, `RadioGroup`, `Slider`, `Calendar` by input type)",
  select: "`Select` from `@/components/ui/select`",
  option: "`SelectItem` from `@/components/ui/select`",
  optgroup: "`SelectGroup` from `@/components/ui/select`",
  textarea: "`Textarea` from `@/components/ui/textarea`",
  label: "`Label` from `@/components/ui/label`",
  table: "`Table` from `@/components/ui/table`",
  thead: "`TableHeader` from `@/components/ui/table`",
  tbody: "`TableBody` from `@/components/ui/table`",
  tfoot: "`TableFooter` from `@/components/ui/table`",
  tr: "`TableRow` from `@/components/ui/table`",
  td: "`TableCell` from `@/components/ui/table`",
  th: "`TableHead` from `@/components/ui/table`",
  caption: "`TableCaption` from `@/components/ui/table`",
  dialog: "`Dialog` from `@/components/ui/dialog`",
  details: "`Collapsible` from `@/components/ui/collapsible`",
  summary: "`CollapsibleTrigger` from `@/components/ui/collapsible`",
  progress: "`Progress` from `@/components/ui/progress`",
  meter: "`Progress` from `@/components/ui/progress`",
  menu: "`DropdownMenu` from `@/components/ui/dropdown-menu`",
  search: "`Command` from `@/components/ui/command`",
};

export const DEFAULT_CONFIG: StrictLintConfig = {
  root: "src",
  featuresDir: "features",
  ignore: [
    "**/*.d.ts",
    "**/*.gen.*",
    "**/*.generated.*",
    "**/__tests__/**",
    "**/__mocks__/**",
    "**/*.test.*",
    "**/*.spec.*",
    "**/*.stories.*",
  ],
  structure: {
    allow: [
      "app/**",
      "routes/**",
      "components/**",
      "features/*/components/**",
      "features/*/{hooks,composables,types,services,queries,constants,utils,schemas}.{ts,tsx}",
      "features/*/store/**",
      "features/*/index.ts",
      "hooks/**",
      "composables/**",
      "lib/**",
      "providers/**",
      "services/**",
      "store/**",
      "types/**",
      "*.{ts,tsx,js,jsx,css,scss}",
    ],
    deny: [
      { pattern: "**/views/**", message: "`views/` is not part of this structure. Route files belong in `app/` (Vue: `routes/`)." },
      { pattern: "**/stores/**", message: "Use `store/`, not `stores/`." },
      { pattern: "**/pages/**", message: "Use `app/` (Vue: `routes/`), not `pages/`." },
      { pattern: "**/utils/**", message: "Shared utilities belong in `lib/`; feature utilities belong in `features/<feature>/utils.ts`." },
      { pattern: "features/*/hooks/**", message: "A feature exposes hooks as a single `features/<feature>/hooks.ts`, not a folder." },
    ],
    ignore: [],
  },
  components: {
    max: 1,
    ignore: [],
    exemptComments: ["sfc-exempt", "strict-lint-exempt"],
    exemptFileComments: ["sfc-exempt-file", "strict-lint-exempt-file"],
  },
  elements: {
    mode: "deny",
    deny: DEFAULT_DENIED_ELEMENTS,
    allow: LAYOUT_ELEMENTS,
    allowInPaths: ["components/ui/**"],
    exemptComments: ["shadcn-exempt", "strict-lint-exempt"],
    exemptFileComments: ["shadcn-exempt-file", "strict-lint-exempt-file"],
  },
  boundaries: {
    aliases: { "@/": "", "~/": "" },
    layers: [
      { name: "route", files: ["app/**", "routes/**"] },
      { name: "feature", files: ["features/**"] },
      {
        name: "shared",
        files: [
          "components/**", "hooks/**", "composables/**", "lib/**",
          "providers/**", "services/**", "store/**", "types/**",
        ],
      },
    ],
    rules: [
      {
        from: "shared",
        disallow: ["route", "feature"],
        message: "Shared code must not depend on a feature or a route. Anything two features need belongs in the shared layer itself.",
      },
      { from: "feature", disallow: ["route"] },
    ],
    crossFeature: "deny",
    ignoreTypeImports: false,
    ignore: [],
    exemptComments: ["boundary-exempt", "strict-lint-exempt"],
    exemptFileComments: ["boundary-exempt-file", "strict-lint-exempt-file"],
  },
  naming: {
    rules: [
      { files: ["**/*.{ts,js,mts,cts}"], case: "camelCase" },
      { files: ["**/*.{tsx,jsx}"], case: "PascalCase" },
      { files: ["components/ui/**"], case: "kebab-case" },
      { files: ["hooks/**/*.{ts,tsx}"], case: "camelCase", prefix: "use" },
      { files: ["composables/**/*.{ts,tsx}"], case: "camelCase", prefix: "use" },
      { files: ["app/**", "routes/**"], case: "any" },
      { files: ["*.{ts,tsx,js,jsx}"], case: "any" },
    ],
    allowNames: ["index"],
    ignore: [],
    exemptComments: ["naming-exempt", "strict-lint-exempt"],
    exemptFileComments: ["naming-exempt-file", "strict-lint-exempt-file"],
  },
};
